---
# Cloudera playbook

- name: Configure Cloudera Manager Repository
  hosts: cdh_servers
  become_method: sudo
  become: yes
  roles:
    - scm_repo 

- name: Install MIT KDC Server
  hosts: krb5_server
  become_method: sudo
  become: yes
  roles:
    - krb5/server
- name: Install MIT KDC Client
  hosts: all
  become_method: sudo
  become: yes
  roles:
    - { role: krb5/client, when: (krb5_kdc_type is defined) and (krb5_kdc_type != 'none') }

- name: Install Cloudera Manager Agents
  hosts: cdh_servers
  become_method: sudo
  become: yes
  roles:
    - scm_agent 

- name: Install Cloudera Manager Server
  hosts: scm_server  
  become_method: sudo
  become: yes
  roles:
    - scm 


- name: Install CDH
  hosts: scm_server
  become_method: sudo
  become: yes
  roles:
    - cdh_flat 
